version: '3'
services:
    test:
        build:
            context: .
            args:
                MODE: develop
        command: "/bin/bash /entrypoint.sh"
        network_mode: host
        volumes:
            - ./src:/src
    prod:
        build:
            context: .
            args:
                MODE: production
        command: "/bin/bash /entrypoint.sh"
        network_mode: host
