# Generated by Django 2.2.4 on 2020-02-29 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import payment_system.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('user_account', 'User account'), ('taxes_account', 'Taxes account')])),
                ('amount', payment_system.fields.MoneyField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', payment_system.fields.MoneyField(decimal_places=2, max_digits=6)),
                ('status', models.TextField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('rate_calculated', 'Rate calculated')])),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transactions', to='payment_system.Account')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transactions', to='payment_system.Account')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='payment_system.Currency')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='payment_system.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('exchange_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='payment_system.ExchangeRate')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_chain', to='payment_system.PaymentTransaction')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='payment_system.Currency'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(type='taxes_account'), fields=('currency',), name='uniq_taxes_accounts'),
        ),
    ]
