# Generated by Django 2.2.4 on 2020-03-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='taxes_account',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='with_taxes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.TextField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('rate_calculated', 'Rate calculated'), ('rejected', 'rejected'), ('user_money_transmitter', 'User money transmitter')]),
        ),
    ]
