# Generated by Django 2.2.4 on 2020-03-02 15:17

from django.db import migrations
import payment_system.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='spent',
            field=payment_system.fields.MoneyField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
