# Generated by Django 2.2.4 on 2020-02-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0002_auto_20200229_1457'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('type', 'user_account'), ('user__isnull', False)), ('type', 'taxes_account'), _connector='OR'), name='user_account_with_user'),
        ),
    ]
