# Generated by Django 2.2.4 on 2020-03-01 12:44

from django.db import migrations
import payment_system.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0002_auto_20200301_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=payment_system.fields.MoneyField(decimal_places=2, max_digits=6),
        ),
    ]
