# Generated by Django 2.2.4 on 2020-02-29 15:30

from django.db import migrations
import payment_system.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0003_auto_20200229_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='taxes',
            field=payment_system.fields.MoneyField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
