# Generated by Django 2.2.4 on 2020-03-02 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0003_auto_20200302_1933'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set(),
        ),
    ]
